spring:
  application:
    name: finansys-api

  datasource:
    urL: jdbc:mysql://${DATASOURCE_URL}:${PORT_NUMBER}/${DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  private:
    key: ${JWT_PRIVATE_KEY}
  public:
    key: ${JWT_PUBLIC_KEY}

app:
  jwt:
    access-expiration: 3600 # 1 hora em segundos
    refresh-expiration: 2592000 # 30 dias em segundos
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}